name: Deploy Backend

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - dev
          - staging
          - production
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yml'

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/augeo-backend
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=semver,pattern={{version}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Output image digest
        run: echo "Image digest:' ${{ steps.build.outputs.digest }}"

  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main'
    environment:
      name: dev
      url: https://augeo-dev-api.azurewebsites.net

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run database migrations
        run: |
          chmod +x ./infrastructure/scripts/run-migrations.sh
          ./infrastructure/scripts/run-migrations.sh dev
        env:
          DATABASE_URL: ${{ secrets.DEV_DATABASE_URL }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: augeo-dev-api
          images: ghcr.io/${{ github.repository_owner }}/augeo-backend:main-${{ github.sha }}

      - name: Verify deployment
        run: |
          sleep 30
          curl -f https://augeo-dev-api.azurewebsites.net/health || exit 1

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: deploy-dev
    if: github.ref == 'refs/heads/main'
    environment:
      name: staging
      url: https://augeo-staging-api.azurewebsites.net

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run database migrations
        run: |
          chmod +x ./infrastructure/scripts/run-migrations.sh
          ./infrastructure/scripts/run-migrations.sh staging
        env:
          DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: augeo-staging-api
          images: ghcr.io/${{ github.repository_owner }}/augeo-backend:main-${{ github.sha }}

      - name: Verify deployment
        run: |
          sleep 30
          curl -f https://augeo-staging-api.azurewebsites.net/health || exit 1

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
      url: https://api.augeo.app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run database migrations
        run: |
          chmod +x ./infrastructure/scripts/run-migrations.sh
          ./infrastructure/scripts/run-migrations.sh production
        env:
          DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}

      - name: Deploy to staging slot
        uses: azure/webapps-deploy@v3
        with:
          app-name: augeo-production-api
          slot-name: staging
          images: ghcr.io/${{ github.repository_owner }}/augeo-backend:main-${{ github.sha }}

      - name: Verify staging slot
        run: |
          sleep 30
          curl -f https://augeo-production-api-staging.azurewebsites.net/health || exit 1

      - name: Swap slots (Blue-Green deployment)
        run: |
          az webapp deployment slot swap \
            --resource-group augeo-production-rg \
            --name augeo-production-api \
            --slot staging \
            --target-slot production

      - name: Verify production deployment
        run: |
          sleep 30
          curl -f https://api.augeo.app/health || exit 1

      - name: Rollback on failure
        if: failure()
        run: |
          echo "Deployment failed, swapping back to previous version"
          az webapp deployment slot swap \
            --resource-group augeo-production-rg \
            --name augeo-production-api \
            --slot staging \
            --target-slot production
